using SignalGo.CodeGenerator.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace SignalGo.CodeGenerator.Helpers
{
    public abstract class ProjectInfoBase
    {
        public ProjectItemsInfoBase ProjectItemsInfoBase { get; set; }
    }

    public abstract class ProjectItemsInfoBase
    {

    }

    public abstract class ProjectItemInfoBase
    {
        public abstract int GetFileCount();
        public abstract string GetFileName(short index);
    }

    public abstract class LanguageMapBase
    {
        protected internal static LanguageMapBase GetCurrent { get; set; }

        public abstract string GetAutoGeneratedText();

        public abstract string DownloadService(string servicePath, AddReferenceConfigInfo config);

        public abstract ProjectInfoBase GetActiveProject();

        public abstract List<ProjectItemInfoBase> GetAllProjectItemsWithoutServices(ProjectItemsInfoBase project);
    }
}
