using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace SignalGo.CodeGenerator.LanguageMaps
{
    public class XMLToCsharp2
    {
        SoapResult _SoapResult;
        public SoapResult Generate(string url, SoapResult soapResult = null)
        {
            if (soapResult == null)
                soapResult = new SoapResult();
            if (soapResult.UrlGenerated.Contains(url))
                return soapResult;
            else
                soapResult.UrlGenerated.Add(url);
            _SoapResult = soapResult;
            using (WebClient client = new WebClient())
            {
                string content = client.DownloadString(url);
                XDocument doc = XDocument.Parse(content);

                if (doc.Elements().FirstOrDefault().Attribute("name") != null)
                {
                    string className = doc.Elements().FirstOrDefault().Attribute("name").Value;
                    soapResult.Classes.Add(new ClassInfo()
                    {
                        Name = className,
                        TargetNameSpace = doc.Elements().FirstOrDefault().Attribute("targetNamespace").Value,
                        Url = url.Substring(0, url.LastIndexOf("wsdl", StringComparison.OrdinalIgnoreCase)) + "service"
                    });
                }
                else
                {
                    //BaseClassInfo = new ClassInfo() { Name = "NoName", TargetNameSpace = doc.Elements().FirstOrDefault().Attribute("targetNamespace")?.Value, Url = url.Substring(0, url.LastIndexOf("wsdl", StringComparison.OrdinalIgnoreCase)) + "service" };
                }
                XmlReader(doc, url);
                foreach (var item in soapResult.Classes.ToList())
                {
                    if (soapResult.Enums.Any(x => x.Name == item.Name) && item.Properties.Count == 0)
                        soapResult.Classes.Remove(item);
                }
                return soapResult;
            }
        }

        public string GeneratesharpCode()
        {
            StringBuilder stringBuilder = new StringBuilder();
            //stringBuilder.AppendLine(LanguageMapBase.GetCurrent.GetAutoGeneratedText());
            stringBuilder.AppendLine("using System;");
            stringBuilder.AppendLine("using SignalGo.Client;");
            stringBuilder.AppendLine("using SignalGo.Shared.DataTypes;");
            stringBuilder.AppendLine("using System.Xml.Serialization;");
            //fix properties instances
            bool canBreack = true;
            //do
            //{
            //    canBreack = true;
            //    foreach (ClassInfo classInfo in _SoapResult.Classes)
            //    {
            //        if (_SoapResult.ClassesToSimpleType.ContainsKey(classInfo.Name))
            //            continue;
            //        if (_SoapResult.ReferenceAttributeGroup.TryGetValue(classInfo.Name, out List<string> items))
            //        {
            //            foreach (var item in items)
            //            {
            //                if (_SoapResult.ReferenceAttributeGroup.TryGetValue(item, out List<string> baseNames))

            //                    var find = _SoapResult.Classes.FirstOrDefault(x => x.Name == item);
            //                foreach (var p in find.Properties)
            //                {
            //                    if (!classInfo.Properties.Any(x => x.Name == p.Name))
            //                    {
            //                        canBreack = false;
            //                        classInfo.Properties.Add(p);
            //                    }
            //                }
            //            }
            //        }
            //    }
            //}
            //while (!canBreack);
            List<string> emptyClasses = _SoapResult.Classes.Where(x => x.Properties.Count == 0 && x.Methods.Count == 0 && !_SoapResult.ClassesToSimpleType.ContainsKey(x.Name) && !_SoapResult.ReferenceAttributeGroup.ContainsKey(x.Name)).Select(x => x.Name).ToList();
            var data = string.Join("\",\"", emptyClasses.ToArray());
            foreach (ClassInfo classInfo in _SoapResult.Classes)
            {
                if (_SoapResult.ClassesToSimpleType.ContainsKey(classInfo.Name) || classInfo.IsArray)
                    continue;

                //if (_SoapResult.ReferenceAttributeGroup.TryGetValue(classInfo.Name, out List<string> items))
                //{
                //    foreach (var item in items)
                //    {
                //        var find = _SoapResult.Classes.FirstOrDefault(x => x.Name == item);
                //        foreach (var p in find.Properties)
                //        {
                //            if (!classInfo.Properties.Any(x => x.Name == p.Name))
                //                classInfo.Properties.Add(p);
                //        }
                //    }
                //}
                if (!string.IsNullOrEmpty(classInfo.TargetNameSpace))
                {
                    stringBuilder.AppendLine($"\t[Serializable]");
                    stringBuilder.AppendLine($"\t[XmlRoot(\"{classInfo.Name}\", Namespace = \"{classInfo.TargetNameSpace}\")]");
                    stringBuilder.AppendLine($"\t[XmlType(\"{classInfo.Name}\", Namespace = \"{classInfo.TargetNameSpace}\")]");
                    //stringBuilder.AppendLine($"\t[XMLSpace(\"{classInfo.TargetNameSpace}\")]");
                }

                string inheritance = "";
                if (_SoapResult.ReferenceAttributeGroup.TryGetValue(classInfo.Name, out List<string> items))
                {
                    inheritance = ": " + items.First();
                }
                stringBuilder.AppendLine($"\tpublic class {classInfo.Name} {inheritance}");
                stringBuilder.AppendLine("\t{");

                //if (!string.IsNullOrEmpty(classInfo.TargetNameSpace))
                //{
                //    stringBuilder.AppendLine("\t\tpublic string TargetNameSpace { get; set; } = \"" + classInfo.TargetNameSpace + "\";");
                //}
                //if (!string.IsNullOrEmpty(classInfo.Url))
                //{
                //    stringBuilder.AppendLine("\t\tpublic string Url { get; set; } = \"" + classInfo.Url + "\";");
                //}

                foreach (MethodInfo method in classInfo.Methods)
                {
                    string returnType = method.ReturnType;
                    if (returnType == "void")
                        returnType = "object";
                    if (_SoapResult.MessagesTypes.TryGetValue(returnType, out string newReturnType))
                        returnType = newReturnType;
                    returnType = returnType.Split(':').LastOrDefault();
                    stringBuilder.AppendLine($"\t\tpublic {returnType} {method.Name}({GetParameterString(method.ParameterInfoes)})");
                    stringBuilder.AppendLine("\t\t{");
                    string url = classInfo.Url?.TrimEnd('/');
                    if (!string.IsNullOrEmpty(url))
                        url += '/';
                    if (_SoapResult.ClassesToSimpleType.TryGetValue(returnType, out List<string> simpleItems))
                    {
                        returnType = simpleItems.First();
                    }
                    stringBuilder.AppendLine($"\t\treturn SignalGo.Client.WebServiceProtocolHelper.CallWebServiceMethod<{(method.ReturnClassType == null ? returnType : method.ReturnClassType.Name)}>(HeaderTemplate,Url,\"{url + method.SoapAction}\", TargetNameSpace,\"{method.Name}\", new SignalGo.Shared.Models.ParameterInfo[]");
                    stringBuilder.AppendLine("\t\t{");
                    foreach (ParameterInfo parameter in method.ParameterInfoes)
                    {
                        stringBuilder.AppendLine($"\t\t new SignalGo.Shared.Models.ParameterInfo(){{ Name = \"{parameter.Name}\",Value = WebServiceProtocolHelper.Serialize({parameter.Name},TargetNameSpace) }},");
                    }
                    stringBuilder.AppendLine("\t\t});");
                    stringBuilder.AppendLine("\t\t}");
                }
                foreach (PropertyInfo property in classInfo.Properties)
                {
                    if (property.ReturnType == null)
                        property.ReturnType = property.Name;
                    string typeName = property.ReturnType.Split(':').LastOrDefault();
                    var classData = _SoapResult.Classes.FirstOrDefault(x => x.Name == typeName);
                    if (classData != null && classData.IsArray)
                    {
                        string arrayType = classData.Type;
                        if (_SoapResult.ClassesToSimpleType.TryGetValue(arrayType, out List<string> simpleItems))
                        {
                            arrayType = simpleItems.First();
                        }
                        GetTypeName(ref arrayType);
                        typeName = $"{arrayType}[]";
                    }
                    else
                    {
                        if (_SoapResult.ScheamaElements.TryGetValue(typeName, out string value) && !_SoapResult.Classes.Any(x => x.Name == typeName) && !_SoapResult.Enums.Any(x => x.Name == typeName))
                            typeName = value.Split(':').LastOrDefault();
                        GetTypeName(ref typeName);
                        if (_SoapResult.ClassesToSimpleType.TryGetValue(typeName, out List<string> simpleItems))
                        {
                            typeName = simpleItems.First();
                        }
                    }
                    if (typeName == "void")
                        continue;
                    string propertyName = property.Name;
                    if (IsDefaultTypes(property.Name) || propertyName == classInfo.Name)
                    {
                        propertyName = "_" + property.Name;
                    }

                    if (string.IsNullOrEmpty(typeName) || (!_SoapResult.Classes.Any(x => x.Name == typeName) && !_SoapResult.Enums.Any(x => x.Name == typeName) && !IsDefaultTypes(typeName)))
                        typeName = "object";
                    if (property.XmlType == XmlType.Attribute)
                        stringBuilder.AppendLine($"\t\t[XmlAttribute(AttributeName = \"{property.Name}\")]");
                    else if (property.XmlType == XmlType.Element)
                        stringBuilder.AppendLine($"\t\t[XmlElement(ElementName=\"{property.Name}\")]");
                    stringBuilder.Append($"\t\tpublic {typeName} {propertyName}{{ get; set; }}");
                    if (property.Name == "Url")
                        stringBuilder.Append($"= \"" + classInfo.Url + "\";");
                    else if (property.Name == "TargetNameSpace" && !string.IsNullOrWhiteSpace(classInfo.TargetNameSpace))
                        stringBuilder.Append($"= \"" + classInfo.TargetNameSpace + "\";");

                    stringBuilder.AppendLine();
                }
                stringBuilder.AppendLine("\t}");
            }
            foreach (EnumInfo enumInfo in _SoapResult.Enums)
            {
                if (enumInfo.Name != enumInfo.BaseName)
                {
                    if (_SoapResult.ClassesToSimpleType.TryGetValue(enumInfo.Name, out List<string> items))
                    {
                        var typeName = items.First();
                        if (GetTypeName(ref typeName))
                            enumInfo.Name = enumInfo.BaseName;
                    }
                }
            }
            foreach (EnumInfo enumInfo in _SoapResult.Enums)
            {
                stringBuilder.AppendLine($"\tpublic enum {enumInfo.Name}");
                stringBuilder.AppendLine("\t{");
                foreach (PropertyInfo property in enumInfo.Properties)
                {
                    stringBuilder.AppendLine($"\t\t{property.Name},");
                }
                stringBuilder.AppendLine("\t}");
            }
            return stringBuilder.ToString();
        }

        private string GetParameterString(List<ParameterInfo> parameterInfoes)
        {
            List<string> result = new List<string>();
            foreach (ParameterInfo item in parameterInfoes)
            {
                string typeName = item.Type;
                if (!_SoapResult.Classes.Any(x => x.Name == typeName))
                {
                    var myType = _SoapResult.Classes.SelectMany(x => x.Properties).FirstOrDefault(x => x.ReturnType == typeName)?.ReturnType;
                    if (myType != null)
                        typeName = myType;
                    if (string.IsNullOrEmpty(typeName))
                        typeName = _SoapResult.Classes.SelectMany(x => x.Properties).FirstOrDefault(x => x.ReturnType == typeName)?.Name;
                }
                if (_SoapResult.ClassesToSimpleType.TryGetValue(typeName, out List<string> simpleItems))
                {
                    typeName = simpleItems.First();
                }
                if (IsDefaultTypes(item.Name))
                    item.Name += "_" + item.Name;
                if (_SoapResult.MessagesTypes.TryGetValue(typeName, out string myTypeName))
                    typeName = myTypeName;
                typeName = typeName.Split(':').LastOrDefault();
                result.Add(typeName + " " + item.Name?.Split('.').FirstOrDefault());
            }
            return string.Join(", ", result);
        }

        public void GenerateElements(ElementInfo parent, IEnumerable<XElement> elements)
        {
            foreach (var item in elements)
            {
                var element = new ElementInfo()
                {
                    Element = item,
                    TargetNameSpace = GetTargetNameSpace(item)
                };
                parent.Add(element);
                GenerateElements(element, item.Elements());
            }
        }


        private void XmlReader(XContainer doc, string url)
        {
            try
            {
                ElementInfo rootElement = new ElementInfo() { };
                GenerateElements(rootElement, doc.Elements());
                var allElements = FindElementTree(rootElement, "element");
                foreach (var attributeGroup in FindElementTree(rootElement, "attributeGroup"))
                {
                    GenerateAttributeGroupType(attributeGroup);
                }
                foreach (var complexType in FindElementTree(rootElement, "complexType"))
                {
                    GenerateType(complexType);
                }
                foreach (var simpleType in FindElementTree(rootElement, "simpleType"))
                {
                    GenerateType(simpleType);
                }
                foreach (var messageType in FindElementTree(rootElement, "message"))
                {
                    GenerateMessageType(allElements, messageType);
                }
                foreach (var item in FindElementTree(rootElement, "schema"))
                {
                    foreach (var element in item.Element.Elements().Where(x => x.Name.LocalName == "element"))
                    {
                        string name = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                        string type = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("type"))?.Value;
                        if (name != null && type != null)
                        {
                            _SoapResult.ScheamaElements.Add(name, type);
                        }
                    }
                }

                foreach (var item in FindElementTree(rootElement, "include"))
                {
                    var location = "/" + item.Element.Attributes().Where(x => x.Name.LocalName == "schemaLocation").Select(x => x.Value).FirstOrDefault();
                    if (location == null)
                        continue;
                    XMLToCsharp2 xMLToCsharp2 = new XMLToCsharp2();
                    var aStringBuilder = new StringBuilder(url);
                    var endIndex = url.IndexOf('?');
                    var startIndex = url.LastIndexOf('/', endIndex);
                    aStringBuilder.Remove(startIndex, endIndex - startIndex);
                    aStringBuilder.Insert(startIndex, location);
                    string myUrl = aStringBuilder.ToString();
                    var classes = xMLToCsharp2.Generate(myUrl, _SoapResult);
                }

                foreach (var item in FindElementTree(rootElement, "portType"))
                {
                    GenerateServiceType(rootElement, item);
                }

            }
            catch (Exception ex)
            {

            }
        }


        private IEnumerable<ElementInfo> FindElementTree(ElementInfo elementInfo, string elementName, string skipName)
        {
            List<ElementInfo> result = new List<ElementInfo>();
            foreach (var element in elementInfo.Children)
            {
                if (element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals(skipName)) == null)
                    continue;
                if (element.Name.LocalName == elementName)
                    result.Add(element);
                result.AddRange(FindElementTree(element, elementName, skipName));
            }
            return result;
        }


        private IEnumerable<ElementInfo> FindElementTree(ElementInfo elementInfo, string elementName)
        {
            List<ElementInfo> result = new List<ElementInfo>();
            foreach (var element in elementInfo.Children)
            {
                if (element.Name.LocalName == elementName)
                    result.Add(element);
                result.AddRange(FindElementTree(element, elementName));
            }
            return result;
        }
        private IEnumerable<ElementInfo> FindElementOnLevel(ElementInfo elementInfo, string elementName)
        {
            List<ElementInfo> result = new List<ElementInfo>();
            foreach (var element in elementInfo.Children)
            {
                if (element.Name.LocalName == elementName)
                    result.Add(element);
            }
            return result;
        }
        string GetTargetNameSpace(XElement element)
        {
            return element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("targetnamespace", StringComparison.OrdinalIgnoreCase))?.Value;
        }

        private void GenerateAttributeGroupType(ElementInfo element)
        {
            try
            {
                string className = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                string referenceName = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("ref"))?.Value;
                string parentName = element.GetParentName();
                if (!string.IsNullOrEmpty(referenceName) && !string.IsNullOrEmpty(parentName))
                {
                    if (_SoapResult.ReferenceAttributeGroup.TryGetValue(parentName, out List<string> result))
                    {
                        if (!result.Contains(referenceName))
                            result.Add(referenceName);
                    }
                    else
                    {
                        var items = _SoapResult.ReferenceAttributeGroup[parentName] = new List<string>();
                        items.Add(referenceName);
                    }
                }
                ClassInfo classInfo = _SoapResult.Classes.FirstOrDefault(x => x.Name == className);
                if (classInfo == null)
                {
                    if (GetTypeName(ref className) || string.IsNullOrEmpty(className))
                        return;
                    classInfo = new ClassInfo()
                    {
                        Name = className,
                        TargetNameSpace = element.GetNearNameSpace()
                    };
                }

                foreach (var item in FindElementTree(element, "attribute"))
                {
                    var name = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"));
                    var type = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("type"));
                    if (name == null)
                        continue;
                    else if (type == null)
                        type = name;
                    if (classInfo.Properties.Any(x => x.Name == name.Value))
                        continue;
                    var realName = name.Value;
                    if (realName == classInfo.Name)
                        realName = ToCacemlCase(realName);
                    classInfo.Properties.Add(new PropertyInfo()
                    {
                        Name = realName,
                        ReturnType = type.Value
                     ,
                        XmlType = XmlType.Attribute
                    });
                }
                if (!_SoapResult.Classes.Contains(classInfo))
                    _SoapResult.Classes.Add(classInfo);
                AddClassToSimpleType(classInfo, element);

            }
            catch (Exception ex)
            {

            }
        }


        private void GenerateType(ElementInfo element)
        {
            try
            {
                var elementName = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                ElementInfo item = element;
                foreach (var elementItem in element.Children)
                {
                    var parent = elementItem.Parent;
                    var parentName = parent.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"));
                    string name = elementName;
                    if (string.IsNullOrEmpty(name))
                    {
                        if (parentName != null)
                        {
                            name = parentName.Value;
                            item = parent;
                        }
                        else
                        {
                            name = parent.Parent.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                            item = parent.Parent;
                        }
                    }
                    if (name == null)
                        continue;
                    name = name.Split('.').LastOrDefault();
                    if (IsEnum(item, out string enumName))
                    {
                        if (string.IsNullOrEmpty(name))
                            name = enumName;
                        else if (string.IsNullOrEmpty(enumName))
                            enumName = name;
                        //if (string.IsNullOrEmpty(enumName))
                        //    enumName = name;
                        //if (!string.IsNullOrEmpty(enumName))
                        //    enumName = enumName.Split(':').LastOrDefault();
                        //if (enumName == "string")
                        //{
                        //    enumName = name;
                        //}
                        EnumInfo enumInfo = _SoapResult.Enums.FirstOrDefault(x => x.Name == name);
                        if (enumInfo == null)
                            enumInfo = new EnumInfo() { Name = name, BaseName = name };
                        GenerateEnums(enumInfo, item.Children);
                    }
                    else
                    {

                        ClassInfo classInfo = _SoapResult.Classes.FirstOrDefault(x => x.Name == name);
                        if (classInfo == null)
                        {
                            if (GetTypeName(ref name))
                                continue;
                            classInfo = new ClassInfo()
                            {
                                Name = name,
                                TargetNameSpace = item.GetNearNameSpace()
                            };
                        }

                        if (IsList(item, out string listType))
                        {
                            classInfo.IsArray = true;
                            classInfo.Type = listType;
                        }
                        GenerateProperties(classInfo, item);
                        AddClassToSimpleType(classInfo, element);
                    }
                }
            }
            catch (Exception ex)
            {

            }
        }
        private void GenerateMessageType(IEnumerable<ElementInfo> allElements, ElementInfo elementInfo)
        {
            try
            {
                var className = elementInfo.Element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name")).Value;
                //ClassInfo classInfo = _SoapResult.Classes.FirstOrDefault(x => x.Name == className);
                //if (classInfo == null)
                //{
                //    if (GetTypeName(ref className))
                //        return;
                //    classInfo = new ClassInfo()
                //    {
                //        Name = className,
                //        TargetNameSpace = elementInfo.TargetNameSpace
                //    };
                //}
                foreach (var item in FindElementTree(elementInfo, "part"))
                {
                    var name = item.Element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"));
                    var typeName = item.Element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("type"));
                    if (typeName == null)
                        typeName = item.Element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("element"));
                    if (name == null || typeName == null)
                        continue;

                    if (!_SoapResult.MessagesTypes.ContainsKey(className))
                    {
                        _SoapResult.MessagesTypes[className] = typeName.Value;
                        break;
                    }
                    //if (classInfo.Properties.Any(x => x.Name == name.Value))
                    //    continue;
                    //var type = typeName.Value.Split(':').LastOrDefault();
                    //var find = allElements.FirstOrDefault(y => y.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value == type && y.Attributes().Any(x => x.Name.LocalName.Equals("type")));
                    //if (find != null)
                    //    type = find.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("type")).Value;
                    //classInfo.Properties.Add(new PropertyInfo() { Name = name.Value, ReturnType = type.Split(':').LastOrDefault(), XmlType = XmlType.Element });
                }
                //if (!_SoapResult.Classes.Contains(classInfo))
                //    _SoapResult.Classes.Add(classInfo);
            }
            catch (Exception ex)
            {

            }
        }



        public bool IsEnum(ElementInfo element, out string enumName)
        {
            enumName = null;
            var items = FindElementOnLevel(element, "restriction").ToList();
            if (element.Name.LocalName == "restriction")
                items.Add(element);
            foreach (var item in items)
            {
                enumName = item.Element.Parent.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                if (string.IsNullOrEmpty(enumName))
                    enumName = item.Element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("base"))?.Value;
                if (FindElementOnLevel(item, "enumeration").Count() > 0)
                {
                    return true;
                }
            }

            foreach (var item in FindElementOnLevel(element, "union"))
            {
                foreach (var item2 in FindElementOnLevel(item, "simpleType"))
                {
                    var isEnum = IsEnum(item2, out enumName);
                    if (isEnum)
                        return true;
                }
            }
            foreach (var item2 in FindElementOnLevel(element, "simpleType"))
            {
                var isEnum = IsEnum(item2, out enumName);
                if (isEnum)
                    return true;
            }
            return false;
        }



        void AddClassToSimpleType(ClassInfo classInfo, ElementInfo element)
        {
            var bases = GetBaseName(element).ToList();
            if (bases.Count() == 0)
            {
                bases = GetBaseName2(element).ToList();
                if (bases.Count > 0)
                {

                }
            }
            if (bases.Count > 0)
            {
                string name = bases.First().Split(':').LastOrDefault();
                List<string> classNames = new List<string>() { classInfo.Name };
                CheckAgain:
                if (GetTypeName(ref name))
                {
                    List<string> newClassCheck = new List<string>();
                    foreach (var className in classNames)
                    {
                        if (_SoapResult.ClassesToSimpleType.TryGetValue(className, out List<string> items))
                        {
                            if (!items.Contains(name))
                                items.Add(name);
                        }
                        else
                        {
                            items = new List<string>();
                            items.Add(name);
                            _SoapResult.ClassesToSimpleType[className] = items;
                        }
                        if (_SoapResult.CanClassToBeSimpleType.TryGetValue(className, out List<string> items2))
                        {
                            newClassCheck.AddRange(items2);
                        }
                    }
                    if (newClassCheck.Count > 0)
                    {
                        classNames.Clear();
                        classNames.AddRange(newClassCheck);
                        goto CheckAgain;
                    }

                }
                else if (_SoapResult.ClassesToSimpleType.TryGetValue(name, out List<string> items))
                {
                    classNames.Add(items.First());
                    name = items.First();
                    goto CheckAgain;
                }
                else
                {
                    if (_SoapResult.CanClassToBeSimpleType.TryGetValue(name, out List<string> items2))
                    {
                        foreach (var item in classNames)
                        {
                            if (!items2.Contains(item))
                                items2.Add(item);
                        }

                    }
                    else
                    {
                        items2 = new List<string>();
                        foreach (var item in classNames)
                        {
                            items2.Add(item);
                        }
                        _SoapResult.CanClassToBeSimpleType[name] = items2;
                    }
                }

            }
        }
        public IEnumerable<string> GetBaseName2(ElementInfo element)
        {
            foreach (var item in FindElementOnLevel(element, "union"))
            {
                var baseName = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("memberTypes"))?.Value;
                if (string.IsNullOrEmpty(baseName))
                {
                    var simpleTypes = FindElementOnLevel(element, "simpleType");
                    foreach (var simpleType in simpleTypes)
                    {
                        baseName = simpleType.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("base"))?.Value;
                        if (!string.IsNullOrEmpty(baseName))
                            break;
                    }
                }
                else
                {
                    foreach (var bn in baseName.Split(' '))
                    {
                        if (!string.IsNullOrEmpty(bn))
                            yield return bn;
                    }
                }

            }
        }
        public IEnumerable<string> GetBaseName(ElementInfo element)
        {
            foreach (var item in FindElementOnLevel(element, "restriction"))
            {
                var baseName = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("base"))?.Value;
                if (!string.IsNullOrEmpty(baseName))
                    yield return baseName;
            }
        }
        public bool IsList(ElementInfo element, out string listType)
        {
            listType = "";
            if (element.Name.LocalName == "list")
            {
                listType = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("itemType"))?.Value;
                if (!string.IsNullOrEmpty(listType))
                    return true;
            }
            foreach (var item in FindElementOnLevel(element, "list"))
            {
                listType = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("itemType"))?.Value;
                if (!string.IsNullOrEmpty(listType))
                    return true;
            }
            return false;
        }

        private void GenerateEnums(EnumInfo enumInfo, IEnumerable<ElementInfo> items)
        {
            try
            {
                foreach (var item in items)
                {
                    if (item.Name.LocalName == "enumeration")
                    {
                        var name = item.Element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("value"))?.Value.Replace('-', '_').Replace(' ', '_');
                        if (!enumInfo.Properties.Any(x => x.Name == name))
                        {
                            enumInfo.Properties.Add(new PropertyInfo() { Name = name });
                        }
                    }
                    foreach (var element in FindElementTree(item, "enumeration"))
                    {
                        var name = element.Element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("value"))?.Value.Replace('-', '_').Replace(' ', '_');
                        if (enumInfo.Properties.Any(x => x.Name == name))
                            continue;
                        enumInfo.Properties.Add(new PropertyInfo() { Name = name });
                    }
                }
                if (!_SoapResult.Enums.Contains(enumInfo))
                    _SoapResult.Enums.Add(enumInfo);
            }
            catch (Exception ex)
            {

            }
        }
        private void GenerateProperties(ClassInfo classInfo, ElementInfo item)
        {
            try
            {
                foreach (var element in FindElementTree(item, "element"))
                {
                    var name = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"));
                    var type = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("type"));
                    if (name == null)
                        continue;
                    else if (type == null)
                        type = FindElementType(element);
                    string realName = name.Value;

                    if (realName == classInfo.Name)
                        realName = ToCacemlCase(realName);
                    if (classInfo.Properties.Any(x => x.Name == realName))
                        continue;
                    classInfo.Properties.Add(new PropertyInfo() { Name = realName, ReturnType = type?.Value, XmlType = XmlType.Element });
                }
                foreach (var element in FindElementTree(item, "attribute"))
                {
                    var name = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"));
                    var type = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("type"));
                    if (name == null)
                        continue;
                    else if (type == null)
                        type = FindElementType(element);
                    string realName = name.Value;

                    if (realName == classInfo.Name)
                        realName = ToCacemlCase(realName);
                    if (classInfo.Properties.Any(x => x.Name == realName))
                        continue;
                    if (type == null)
                        type = name;
                    classInfo.Properties.Add(new PropertyInfo() { Name = realName, ReturnType = type?.Value.Split(':').LastOrDefault(), XmlType = XmlType.Attribute });
                }
                if (!_SoapResult.Classes.Contains(classInfo))
                    _SoapResult.Classes.Add(classInfo);
            }
            catch (Exception ex)
            {

            }
        }

        XAttribute FindElementType(ElementInfo item)
        {
            foreach (var element in FindElementTree(item, "extension"))
            {
                return element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("base"));
            }

            foreach (var element in FindElementTree(item, "attributeGroup"))
            {
                return element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("ref"));
            }
            foreach (var element in FindElementTree(item, "extension"))
            {
                return element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("base"));
            }
            foreach (var element in FindElementTree(item, "extension"))
            {
                return element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("base"));
            }
            //foreach (var element in FindElementOnLevel(item, "simpleType"))
            //{
            //    foreach (var item2 in FindElementOnLevel(element, "restriction"))
            //    {
            //        return item2.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("base"));

            //    }
            //}
            return null;
        }

        string ToCacemlCase(string text)
        {
            if (string.IsNullOrEmpty(text))
                return text;
            else if (text.Length == 1)
                return text.ToLower();
            return text[0].ToString().ToLower() + text.Substring(1);
        }

        private void GenerateServiceType(ElementInfo rootElement, ElementInfo element)
        {
            try
            {
                ClassInfo serviceClass = new ClassInfo();
                serviceClass.TargetNameSpace = element.GetNearNameSpace();
                serviceClass.Name = element.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name")).Value;
                serviceClass.Properties.Add(new PropertyInfo() { Name = "HeaderTemplate", ReturnType = "string" });
                serviceClass.Properties.Add(new PropertyInfo() { Name = "TargetNameSpace", ReturnType = "string" });
                serviceClass.Properties.Add(new PropertyInfo() { Name = "Url", ReturnType = "string" });
                ElementInfo bindingElement = null;
                string bindingElementName = "";
                foreach (var item in FindElementTree(rootElement, "binding"))
                {
                    var type = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("type"))?.Value;
                    if (string.IsNullOrEmpty(type))
                        continue;
                    type = type.Split(':').LastOrDefault();
                    if (type == serviceClass.Name)
                    {
                        bindingElement = item;
                        bindingElementName = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                        break;
                    }
                }
                foreach (var service in FindElementTree(rootElement, "service"))
                {
                    foreach (var port in FindElementTree(service, "port"))
                    {
                        var binding = port.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("binding"))?.Value.Split(':').LastOrDefault();
                        if (binding == bindingElementName)
                        {
                            var address = FindElementTree(service, "address").FirstOrDefault()?.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("location"))?.Value;
                            serviceClass.Url = address;
                            break;
                        }
                    }
                }

                foreach (var item in FindElementTree(element, "operation"))
                {
                    string methodName = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name")).Value;
                    var methodRetuenElement = FindElementTree(item, "output").FirstOrDefault();
                    var returnType = methodRetuenElement?.Attributes().Where(x => x.Name.LocalName.Equals("name")).FirstOrDefault()?.Value;
                    if (returnType == null)
                        returnType = methodRetuenElement?.Attributes().Where(x => x.Name.LocalName.Equals("message")).FirstOrDefault()?.Value;
                    if (string.IsNullOrEmpty(returnType))
                    {
                        returnType = "object";
                    }
                    returnType = returnType.Split(':').LastOrDefault();
                    var returnClass = _SoapResult.Classes.FirstOrDefault(x => x.Name == returnType);
                    if (returnClass != null && returnClass.Properties.Count == 1)
                    {
                        returnType = returnClass.Properties.First().ReturnType;
                        //name = name + "." + returnClass.Properties.First().Name;
                    }
                    GetTypeName(ref returnType);
                    string soapAction = "";
                    foreach (var operation in FindElementTree(bindingElement, "operation"))
                    {
                        string opName = operation.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                        if (opName == methodName)
                        {
                            soapAction = FindSoapAction(operation);
                        }
                    }
                    serviceClass.Methods.Add(new MethodInfo()
                    {
                        SoapAction = soapAction,
                        ReturnType = returnType,
                        Name = methodName,
                        ParameterInfoes = GetMethodParameters(item),
                        //ReturnClassType = methodRetuenElement.Where(x => x.Name.LocalName.Equals("name")).FirstOrDefault()?.Value
                    });
                }
                _SoapResult.Classes.Add(serviceClass);
            }
            catch (Exception ex)
            {

            }
        }

        string FindSoapAction(ElementInfo element)
        {
            List<XElement> elements = new List<XElement>();
            FindAllElements(element.Element, elements);
            foreach (var item in elements)
            {
                string soapAtion = item.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("soapAction", StringComparison.OrdinalIgnoreCase))?.Value;
                if (!string.IsNullOrEmpty(soapAtion))
                    return soapAtion;
            }
            return null;
        }
        private void GenerateMethods(ClassInfo classInfo, ElementInfo elementInfo)
        {
            try
            {
                foreach (var item in elementInfo.Children)
                {
                    GenerateMethods(classInfo, item);
                    if (item.Name.LocalName == "element")
                    {
                        var parent = FindMethodName(item);
                        if (parent == null)
                            continue;
                        string methodName = parent.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name")).Value;
                        if (classInfo.SkipMethods.Contains(methodName))
                            continue;
                        string methodReponse = GetMethodResponse(parent, methodName, out ClassInfo returnType);

                        if (!string.IsNullOrEmpty(methodReponse))
                            classInfo.Methods.Add(new MethodInfo() { ReturnType = methodReponse, Name = methodName, ParameterInfoes = GetMethodParameters(parent), ReturnClassType = returnType });
                        Console.WriteLine(item.Element.NodeType + " " + item);
                    }
                }
            }
            catch (Exception ex)
            {

            }
        }

        private string GetMethodResponse(ElementInfo element, string name, out ClassInfo returnType)
        {
            returnType = null;
            if (!(element.Element.NextNode is XElement node))
                return null;
            XAttribute attribute = node.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"));
            if (attribute != null && attribute.Value == name + "Response")
            {
                string className = name + "Response";
                //if (BaseClassInfo.SkipMethods.Contains(className))
                //    return null;
                //BaseClassInfo.SkipMethods.Add(className);
                List<XElement> elements = new List<XElement>();
                FindAllElements(node, "element", elements);
                if (elements.Count > 1)
                {
                    StringBuilder classBuilder = new StringBuilder();
                    if (GetTypeName(ref className))
                        return null;
                    ClassInfo classInfo = new ClassInfo() { Name = className };
                    foreach (XElement item in elements)
                    {
                        classInfo.Properties.Add(new PropertyInfo() { ReturnType = CleanType(item.Attribute("type").Value), Name = item.Attribute("name").Value, XmlType = XmlType.Element });
                    }
                    _SoapResult.Classes.Add(classInfo);
                    returnType = classInfo;
                    return className;
                }
                else if (elements.Count == 1)
                {
                    XElement first = elements.First();
                    return CleanType(first.Attribute("type").Value);
                }
                else
                {
                    return "void";
                }
            }
            return "void";
        }

        private string CleanType(string value)
        {
            if (value.Contains(":"))
            {
                return value.Substring(value.LastIndexOf(":") + 1);
            }
            return value;
        }

        private void FindAllElements(XElement element, string elementTagName, List<XElement> elements)
        {
            foreach (var item in element.Elements())
            {
                if (item.Name.LocalName == elementTagName)
                    elements.Add(item);
                FindAllElements(item, elementTagName, elements);
            }
        }

        private void FindAllElements(XElement element, List<XElement> elements)
        {
            foreach (var item in element.Elements())
            {
                elements.Add(item);
                FindAllElements(item, elements);
            }
        }

        static Dictionary<string, string> DefaultTypes { get; set; } = new Dictionary<string, string>()
        {
            //{ "ArrayOfString","string[]"},
            //{ "ArrayOfInt","int[]"},
            //{ "ArrayOfLong","long[]"},
            //{ "base64Binary","byte[]"},
            { "boolean","bool"},
            { "dateTime","DateTime"},
            { "date","DateTime"},
            { "nonNegativeInteger","uint"},
            { "anyURI","string"},
            { "positiveInteger","uint"},
            { "duration","long"},
            { "language","string"},
            { "String","string"},
            { "integer","int"},
            { "Decimal","decimal"},
            { "base64Binary","byte[]"},
            { "unsignedByte","byte"},
            { "time","DateTime"},
            { "double","double"},
            { "sbyte","sbyte"},
            { "short","short"},
            { "ushort","ushort"},
            { "ulong","ulong"},
        };
        public bool IsDefaultTypes(string name)
        {
            return DefaultTypes.Values.Contains(name);
        }

        public bool GetTypeName(ref string name)
        {
            if (name == null)
                return false;
            if (DefaultTypes.TryGetValue(name, out string value))
            {
                name = value;
                return true;
            }
            else if (DefaultTypes.Values.Contains(name))
            {
                return true;
            }
            return false;
        }


        private List<ParameterInfo> GetMethodParameters(ElementInfo element)
        {
            List<ParameterInfo> result = new List<ParameterInfo>();
            foreach (var item in FindElementTree(element, "input"))
            {
                string name = item.Element.Attribute("name")?.Value;
                if (name == null)
                    name = item.Element.Attribute("message")?.Value;
                if (name != null)
                    name = name.Split(':').LastOrDefault();
                var returnClass = _SoapResult.Classes.FirstOrDefault(x => x.Name == name);
                string type = item.Element.Attribute("message") != null ? CleanType(item.Element.Attribute("message").Value) : null;
                if (returnClass != null && returnClass.Properties.Count == 1)
                {
                    //if (returnClass.Properties.First().ReturnType != returnClass.Properties.First().Name)
                    name = type = returnClass.Properties.First().ReturnType;
                    //name = name + "." + returnClass.Properties.First().Name;
                }
                result.Add(new ParameterInfo()
                {
                    Name = name,
                    Type = type
                });
            }
            return result;
        }

        private ElementInfo FindMethodName(ElementInfo element)
        {
            ElementInfo name = null;
            ElementInfo parent = element.Parent;
            while (parent != null && name == null)
            {
                XAttribute find = parent.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"));
                if (find != null)
                    name = parent;
                parent = parent.Parent;
            }
            return name;
        }
    }
    public class ElementInfo
    {
        public XElement Element { get; set; }
        public XName Name
        {
            get
            {
                return Element.Name;
            }
        }

        public string TargetNameSpace { get; set; }

        public ElementInfo Parent { get; set; }

        public List<ElementInfo> Children { get; set; } = new List<ElementInfo>();

        public string GetNearNameSpace()
        {
            string nameSpace = TargetNameSpace;
            ElementInfo parent = Parent;
            while (string.IsNullOrEmpty(nameSpace) && parent != null)
            {
                nameSpace = parent.TargetNameSpace;
                parent = parent.Parent;
            }
            return nameSpace;
        }

        public void Add(ElementInfo elementInfo)
        {
            Children.Add(elementInfo);
            elementInfo.Parent = this;
        }

        public IEnumerable<XAttribute> Attributes()
        {
            return Element.Attributes();
        }
        public string GetParentName()
        {
            string name = "";
            ElementInfo parent = Parent;
            while (string.IsNullOrEmpty(name) && parent != null)
            {
                if (parent.Element == null)
                    break;
                name = parent.Attributes().FirstOrDefault(x => x.Name.LocalName.Equals("name"))?.Value;
                parent = parent.Parent;
            }
            return name;
        }


    }
    public class SoapResult
    {
        public Dictionary<string, List<string>> ReferenceAttributeGroup { get; set; } = new Dictionary<string, List<string>>();
        public Dictionary<string, List<string>> ClassesToSimpleType { get; set; } = new Dictionary<string, List<string>>();
        public Dictionary<string, List<string>> CanClassToBeSimpleType { get; set; } = new Dictionary<string, List<string>>();
        public List<string> UrlGenerated { get; set; } = new List<string>();
        public List<ClassInfo> Classes { get; set; } = new List<ClassInfo>();
        public List<EnumInfo> Enums { get; set; } = new List<EnumInfo>();
        public Dictionary<string, string> ScheamaElements { get; set; } = new Dictionary<string, string>();
        public Dictionary<string, string> MessagesTypes { get; set; } = new Dictionary<string, string>();
    }

    public class EnumInfo
    {
        public string Name { get; set; }
        public string BaseName { get; set; }
        public List<PropertyInfo> Properties { get; set; } = new List<PropertyInfo>();
    }

    public class ClassInfo
    {
        public string TargetNameSpace { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }
        public List<MethodInfo> Methods { get; set; } = new List<MethodInfo>();
        public List<PropertyInfo> Properties { get; set; } = new List<PropertyInfo>();
        public List<string> SkipMethods { get; set; } = new List<string>();
        public bool IsArray { get; set; }
        public string Type { get; set; }
    }

    public class PropertyInfo
    {
        public XmlType XmlType { get; set; }
        public string Name { get; set; }
        public string ReturnType { get; set; }
    }

    public class MethodInfo
    {
        public string SoapAction { get; set; }
        public string Name { get; set; }
        public string ReturnType { get; set; }
        public ClassInfo ReturnClassType { get; set; }
        public List<ParameterInfo> ParameterInfoes { get; set; } = new List<ParameterInfo>();
    }

    public class ParameterInfo
    {
        public string Name { get; set; }
        public string Type { get; set; }
    }

    public enum XmlType
    {
        Attribute,
        Element
    }
}
